import NavBar from "@/Components/webpage/NavbarComponent"
import Footer from "@/Components/webpage/FooterComponent"
import './globals.css'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div>
          <NavBar />
          <main>{children}</main>
          <Footer/>
        </div>
      </body>
    </html>
  )
}